// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// raster2vector
List raster2vector(NumericMatrix raster, double from, double to, double step, int precision, bool exclave);
RcppExport SEXP fasteraster_raster2vector(SEXP rasterSEXP, SEXP fromSEXP, SEXP toSEXP, SEXP stepSEXP, SEXP precisionSEXP, SEXP exclaveSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type raster(rasterSEXP);
    Rcpp::traits::input_parameter< double >::type from(fromSEXP);
    Rcpp::traits::input_parameter< double >::type to(toSEXP);
    Rcpp::traits::input_parameter< double >::type step(stepSEXP);
    Rcpp::traits::input_parameter< int >::type precision(precisionSEXP);
    Rcpp::traits::input_parameter< bool >::type exclave(exclaveSEXP);
    __result = Rcpp::wrap(raster2vector(raster, from, to, step, precision, exclave));
    return __result;
END_RCPP
}
